server {
  listen 80;
  default_type application/octet-stream;
  client_max_body_size 256M;

  include /etc/nginx/mime.types;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html =404;
  }
}